config/routes.rb
Rails.application.routes.draw do

#-----------------------------------------------------------------

  root :to => 'status#new'

#-----------------------------------------------------------------

  resources :status do
    collection do
      get  :all_status
      get  :status_report
      post :notify_status
      get  :prev_status
    end
  end

  resources :utility  do
    collection do
      get  :risk_document
      get  :edit_risk_sheet
      post :create_risk_sheet
      put  :update_risk_sheet
      delete :remove_risk_sheet
    end
  end
#-----------------------------------------------------------------
# Custom Routes
#-----------------------------------------------------------------

  get '/all_status' => 'status#all_status'
  get '/sr' => 'status#status_report'
  get '/status/prev/:diff' => 'status#prev_status', :as => :previous_status

#-----------------------------------------------------------------

end

app/views/partials/_nav.html.erb
<div class="container nav-container">
  <!-- <div class="navbar-header">
    <a class="navbar-brand" href="#">WebSiteName</a>
  </div> -->
  <ul class="nav navbar-nav">
    <li class="active"><a href="<%=root_path%>">Home</a></li>
    <li><a href="<%=new_status_path%>">Update</a></li>
    <li><a href="<%=all_status_status_index_path%>">People</a></li>
    <li><a href="<%=status_report_status_index_path%>">Report</a></li>
    <li><a onclick="alert('Not implemented Yet!')">History</a></li>
  </ul>
</div>