config/routes.rb
Rails.application.routes.draw do

#-----------------------------------------------------------------

  root :to => 'status#new'

#-----------------------------------------------------------------

  resources :status do
    collection do
      get  :all_status
      get  :status_report
      post :notify_status
      get  :prev_status
    end
  end

  resources :utility  do
    collection do
      get  :risk_document
      get  :edit_risk_sheet
      post :create_risk_sheet
      put  :update_risk_sheet
      delete :remove_risk_sheet
    end
  end
#-----------------------------------------------------------------
# Custom Routes
#-----------------------------------------------------------------

  get '/all_status' => 'status#all_status'
  get '/sr' => 'status#status_report'
  get '/status/prev/:diff' => 'status#prev_status', :as => :previous_status

#-----------------------------------------------------------------

end

app/controllers/utility_controller.rb
class UtilityController < ApplicationController

  def risk_document
    @risk_documents = RiskDocument.all
  end

  def edit_risk_sheet
    if params[:document_id]
      @risk_document = find_risk_document
    else
      @risk_document = RiskDocument.new
    end
  end

  def create_risk_sheet
    @risk_document = RiskDocument.new(risk_document_params)
    if @risk_document.save
      flash[:success] = 'Risk Document Has Been Added Successfully'
      redirect_to risk_document_utility_index_path
    else
      render :edit_risk_sheet
    end
  end

  def update_risk_sheet
    if params[:document_id]
      @risk_document = find_risk_document
      @risk_document.update_attributes(risk_document_params)
      flash[:success] = 'Risk Document Has Been Updated Successfully'
      redirect_to risk_document_utility_index_path
    else
      render :edit_risk_sheet
    end
  end

  def remove_risk_sheet
    if params[:document_id]
      @risk_document = find_risk_document
      @risk_document.update_attribute(:enabled, !@risk_document.enabled)
      flash[:success] = 'Updated!'
      redirect_to risk_document_utility_index_path and return
    end
    redirect_to risk_document_utility_index_path
  end


  def risk_document_params
    params[:risk_document].permit(:feature_id, :feature_link, :feature_name, :status, :prd, :ux, :iteration, :notes)
  end

  private

  def find_risk_document
    return RiskDocument.where(:id => params[:document_id]).first
  end

end

app/helpers/utility_helper.rb
module UtilityHelper
end

app/views/utility/_risk_documents.html.erb
<table class="table table-striped"
style="width: <%=is_website_view ? '100%' : '85%'%>;border: 1px solid black;border-collapse:collapse;font-size:13px;font-family: Arial, Sans-Serif;overflow:auto;table-layout:fixed;text-align:center;height: 30px;">
  <thead>
    <tr style="font-size:13px;background-color: #3E65CF">
      <th style="color:white;border: 1px solid black;text-align: center;height: 30px;width:8%;vertical-align:middle">Feature#</th>
      <th style="color:white;border: 1px solid black;text-align: center;height: 30px;width:18%;vertical-align:middle">
        Feature Planned In Current Iteration
      </th>
      <th style="color:white;border: 1px solid black;text-align: center;height: 30px;width:8%;vertical-align:middle">Status</th>
      <th style="color:white;border: 1px solid black;text-align: center;height: 30px;width:6%;vertical-align:middle">PRD</th>
      <th style="color:white;border: 1px solid black;text-align: center;height: 30px;width:6%;vertical-align:middle">UX</th>
      <th style="color:white;border: 1px solid black;text-align: center;height: 30px;width:15%;vertical-align:middle">Notes/Dependency if any</th>
      <% if is_website_view %>
        <th style="color:white;border: 1px solid black;text-align: center;height: 30px;width:15%;vertical-align:middle"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% risk_documents.each do |rd|%>
      <tr style="font-size:13px;background-color: #F8F8F8;opacity: <%=rd.enabled ? 1 : 0.6 %>">
        <td style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width: 8%;"><%=rd.feature_id!='0' ? (link_to(rd.feature_id, rd.feature_link, :target => :blank)) : ''%></td>
        <td style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width: 8%;"><%=rd.feature_name%></td>
        <td style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width: 8%;"><%=rd.status%></td>
        <td style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width: 8%;"><%=rd.feature_id!='0' ? (rd.prd ? 'Yes' : 'No') : ''%></td>
        <td style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width: 8%;"><%=rd.feature_id!='0' ? (rd.ux ? 'Yes' : 'No') : ''%></td>
        <td style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width: 8%;"><%=rd.notes%></td>
        <% if is_website_view %>
          <td style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width: 8%;">
            <%=link_to 'Edit', edit_risk_sheet_utility_index_path(:document_id => rd.id)%> |
            <%=link_to (rd.enabled ? 'Disable' : 'Enable'), remove_risk_sheet_utility_index_path(:document_id => rd.id), :method => :delete %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/utility/edit_risk_sheet.html.erb
<div class='template no-gutter'>
  <h4>Create Risk Sheet</h4>
  <div class="form m-t-10">
    <%=form_for @risk_document,
      :url => (@risk_document.new_record? ? create_risk_sheet_utility_index_path : update_risk_sheet_utility_index_path(:document_id => @risk_document.id)),
      :method => ( @risk_document.new_record? ? :post : :put) do |form| %>
      <div class="form-group">
        <label class='form-label'>Feature Id</label>
        <%=form.text_field :feature_id%>
        <span class='error'>
          <%=@risk_document.errors[:feature_id][0] if @risk_document.errors[:feature_id]%>
        </span>
      </div>
      <div class="form-group">
        <label class='form-label'>Feature Link</label>
        <%=form.text_field :feature_link%>
        <span class='error'>
          <%=@risk_document.errors[:feature_link][0] if @risk_document.errors[:feature_link]%>
        </span>
      </div>
      <div class="form-group">
        <label class='form-label'>Feature Name</label>
        <%=form.text_field :feature_name%>
        <span class='error'>
          <%=@risk_document.errors[:feature_name][0] if @risk_document.errors[:feature_name]%>
        </span>
      </div>
      <div class="form-group">
        <label class='form-label'>Current Status</label>
        <%=form.text_field :status%>
        <span class='error'>
          <%=@risk_document.errors[:status][0] if @risk_document.errors[:status]%>
        </span>
      </div>
      <div class="form-group">
        <label class='form-label'>Iteration</label>
        <%=form.text_field :iteration, :placeholder => 'Type only 1 for i1'%>
        <span class='error'>
          <%=@risk_document.errors[:iteration][0] if @risk_document.errors[:iteration]%>
        </span>
      </div
      <div class="form-group">
        <label class='form-label'>PRD</label>
        <%=form.check_box :prd, {}%>
      </div>
      <div class="form-group">
        <label class='form-label'>UX</label>
        <%=form.check_box :ux, {}%>
      </div>
      <div class="form-group">
        <label class='form-label'>Notes</label>
        <%=form.text_area :notes%>
      </div>
      <%=form.submit @risk_document.id ? 'Update' : 'Create', :class => 'button'%>
    <% end %>
  </div>
</div>

app/views/utility/risk_document.html.erb
<%=render :partial => 'risk_documents', :locals => {:risk_documents => @risk_documents, :is_website_view => true}%>