config/routes.rb
Rails.application.routes.draw do

#-----------------------------------------------------------------

  root :to => 'status#new'

#-----------------------------------------------------------------

  resources :status do
    collection do
      get  :all_status
      get  :status_report
      post :notify_status
      get  :prev_status
    end
  end

  resources :utility  do
    collection do
      get  :risk_document
      get  :edit_risk_sheet
      post :create_risk_sheet
      put  :update_risk_sheet
      delete :remove_risk_sheet
    end
  end
#-----------------------------------------------------------------
# Custom Routes
#-----------------------------------------------------------------

  get '/all_status' => 'status#all_status'
  get '/sr' => 'status#status_report'
  get '/status/prev/:diff' => 'status#prev_status', :as => :previous_status

#-----------------------------------------------------------------

end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  #delegate :email, :to => :user, :prefix => 'user'

  validates :user_email,
            :presence => true

  attr_accessor  :user_email

  #
  # Associations
  #
  has_many :tasks,
           :dependent => :destroy

  has_many :today_tasks, -> { where('tasks.task_type = ?', Task::TASK_TYPES[:today]) },
           :class_name => 'Task',
           :dependent => :destroy

  has_many :tomorrow_tasks, -> { where('tasks.task_type = ?', Task::TASK_TYPES[:tomorrow]) },
           :class_name => 'Task',
           :dependent => :destroy

  #---------------------------------------------------------------------------------------------------------------------

  accepts_nested_attributes_for :tasks,
                                :allow_destroy => true

  accepts_nested_attributes_for :today_tasks,
                                :allow_destroy => true

  accepts_nested_attributes_for :tomorrow_tasks,
                                :allow_destroy => true

  #---------------------------------------------------------------------------------------------------------------------

  #
  # Validations
  #
  validate :email_of_associated_user, :if => lambda {|status| status.new_record?}
  validate :status_already_added_for_today, :if => lambda {|status| status.new_record?}
  #
  # Callbacks
  #
  before_create :associate_user


  def user_email
    user.try(:email) || @user_email
  end

  def email_of_associated_user
    @user = User.where(email: user_email).first
    self.errors.add(:user_email, "No associated user found in the database with provided email") if @user.blank?
  end

  def status_already_added_for_today
    user_emails = Status.where("Date(created_at) = ? and user_id IS NOT NULL", Date.today).collect{|status| status.user.email}
    if user_emails.include?(user_email)
      self.errors.add(:user_email, "Status with this user has already been created")
    end
  end


  def associate_user
    if @user
      self.user_id = @user.id
    end
  end

  def self.fetch_today_statuses
    ans = Status.includes(:user, :today_tasks, :tomorrow_tasks).where("Date(statuses.created_at) = ?", Date.today).inject({}){|today_statuses, status|
      today_statuses[status.user] = status
      today_statuses
    }
    return Hash[ans.sort_by{|k,v| k.sorder}]
  end

  def self.fetch_prev_day_statuses(diff=1)
    return Status.includes(:user, :today_tasks, :tomorrow_tasks).where("Date(statuses.created_at) = ?", Date.today - diff).inject({}){|today_statuses, status|
      today_statuses[status.user] = status
      today_statuses
    }
  end

end

app/controllers/status_controller.rb
class StatusController < ApplicationController

  #skip_before_filter :verify_authenticity_token, :only => [:notify_status]

  def index
    redirect_to all_status_status_index_path
  end

  def new
    @status = Status.new
    @status.today_tasks.build
    @status.tomorrow_tasks.build
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      session[:status_id] = @status.id
      flash[:success] = "Your status has been successfully added."
      redirect_to status_path(@status)
    else
      render :action => :new
    end
  end

  def show
    @status = Status.find(params[:id])
  end

 def edit
   @status = Status.find(params[:id])
 end

 def update
   @status = Status.find(params[:id])
   if @status.update_attributes(status_params)
     flash[:success] = "Your status has been successfully updated."
     redirect_to status_path(@status)
   else
     render :action => :edit
   end
 end

def destroy
  @status = Status.find(params[:id])
  if @status.destroy
    redirect_to status_report_status_index_path
  end
end

#-----------------------------------------------------------------------------------------

  def all_status
   @users_status = Status.joins(:user).where("Date(statuses.created_at) = ?", Date.today)
  end

#-----------------------------------------------------------------------------------------

  def status_report
   @today_statuses = Status.fetch_today_statuses
   @users_not_updated_status = User.find_who_have_not_updated_status
   @risk_documents = RiskDocument.where(:enabled => true)
   if email_view?
     render :template => 'status/status_report_email.html.erb'
   end
  end

#-----------------------------------------------------------------------------------------

  def prev_status
    diff = params[:diff].to_i
    @today_statuses = Status.fetch_prev_day_statuses(diff)
    @risk_documents = RiskDocument.where(:enabled => true)
    render :template => 'status/status_report.html.erb'
  end

#-----------------------------------------------------------------------------------------

  def notify_status
   @today_statuses = Status.fetch_today_statuses
   @risk_documents = RiskDocument.where(:enabled => true)
   @email_notification = EmailNotification.new(params[:email])
     if @email_notification.valid?
       UserNotifier.send_status(@today_statuses,  @risk_documents, @email_notification.email).deliver
       flash[:success] = "Status has been successfully sent"
       redirect_to status_report_status_index_path
    else
      render :action => :status_report
    end
  end

#---------------------------------------------------------------------------------------------

# PRIVATE #

  private

  def status_params
    params.require(:status).permit(:user_email,
                                   :impediments,
                                   :done,
                                   :tracker_updated,
                                   :today_tasks_attributes    => [:id, :name, :description, :task_type, :_destroy],
                                   :tomorrow_tasks_attributes => [:id, :name, :description, :task_type, :_destroy]
    )
  end

end

app/helpers/status_helper.rb
module StatusHelper

  def link_to_add_more(form_ref, association_name, partial_to_render, locals)
    html_options = {}
    association_instance = form_ref.object.class.reflect_on_association(association_name).klass.new
    view_to_render = form_ref.fields_for(association_name, association_instance, :child_index => '_new_') do |task_builder|
      render(:partial => partial_to_render, :locals => {:form => task_builder, :enable_destroy => true }.merge(locals))
    end
    html_options['data-form-prepend'] = raw CGI::escapeHTML( view_to_render )
    html_options['append-container'] = association_name
    html_options[:class] = 'add-more'
    content_tag(:a, '+Add More', html_options)
  end

  def formatted_description(description)
    return if description.blank?
    description = remove_invalid_chars(description)
    description = "-- " + description.split("\r\n").join("\n-- ")
    simple_format(description, {}, :wrapper_tag => "div")
  end

  def remove_invalid_chars(content)
    content.gsub(/-/, '')
  end

end

app/views/status/_form.html.erb
<div class="template">
  <div class="form">
    <%= form_for @status, :url => (@status.new_record? ? status_index_path : status_path(@status)), :class => 'form-horizontal'  do |form|%>
      <div class="form-group">
        <label class="control-label">Email</label>
        <%=form.text_field :user_email, :class => 'form-control', :placeholder => "Enter globallogic email"%>
        <span class='error'><%=@status.errors[:user_email][0] if @status.errors[:user_email]%></span>
      </div>
      <div class="form-group today_tasks">
        <%=form.label :what_was_done_today, :class => 'control-label'%>
        <%= form.fields_for :today_tasks do |today_task| %>
          <%=render :partial => 'task_fields',
                    :locals => {
                                 :form => today_task,
                                 :status => @status,
                                 :status_task_type => 'today',
                                 :enable_destroy => !today_task.object.new_record? && today_task.index > 0
                              }
          %>
        <% end %>
      </div>
      <div class="form-group">
        <%=link_to_add_more(form, :today_tasks, 'task_fields', { :status => nil, :status_task_type => 'today' })%>
      </div>
      <div class="form-group tomorrow_tasks">
        <%=form.label :plan_for_tomorrow, :class => 'control-label'%>
        <%= form.fields_for :tomorrow_tasks do |tomorrow_task| %>
          <%=render :partial => 'task_fields',
                    :locals => {
                                 :form => tomorrow_task,
                                 :status => @status,
                                 :status_task_type => 'tomorrow',
                                 :enable_destroy => !tomorrow_task.object.new_record? && tomorrow_task.index > 0
                              }
          %>
        <% end %>
      </div>
      <div class="form-group">
        <%=link_to_add_more(form, :tomorrow_tasks, 'task_fields', {  :status => nil, :status_task_type => 'tomorrow' })%>
      </div>
      <div class="form-group">
        <%=form.label :impediments, :class => 'control-label'%>
        <%=form.text_field :impediments, :class => 'form-control'%>
      </div>
      <div class="checkbox">
        <label><%=form.check_box :tracker_updated%> Jira Updated </label>
      </div>
      <div class="form-group">
          <%=form.submit "Submit", :class => 'btn btn-default'%>
      </div>
    <% end %>
  </div>
</div>

app/views/status/_form_for_email.html.erb
<!--
  Email Notify form
-->

<div class="form-email margin-div">
  <h3>Send Email</h3>
  <% if @email_notification %>
    <span class='error'>
      <%=
          "Email "  + @email_notification.errors.messages[:email][0] unless @email_notification.errors.messages[:email].blank?
      %>
    </span>
  <% end %>
  <%= form_tag notify_status_status_index_path do %>
    <div class="form-group">
      <%=text_field_tag "email", '',
                        :class => 'form-control email',
                        :placeholder => "Put email"
      %>
    </div>
    <div class="form-group">
      <%=button_tag 'Submit'%>
    </div>
  <% end %>
</div>

app/views/status/_report_template.html.erb
<div class="clearfix">
  <% unless is_website_view %>
    <div class="">
      <p>
        Hello Everyone, <br/><br/>
        Following is our status for today:-<br/><br/>
      </p>
    </div>
  <% end %>
  <%#=render :partial => 'utility/risk_documents', :locals => {:risk_documents => risk_documents, :is_website_view => false }%>
  <table class="table table-striped"
         style="width: <%=is_website_view ? '100%' : '85%'%>;border: 1px solid black;border-collapse:collapse;font-size:13px;font-family: rial, Sans-Serif;overflow:auto;table-layout:fixed;text-align: center;height: 30px;margin-bottom: 30px;">
    <thead>
      <tr style="font-size:13px;background-color: rgb(153,153,153)">
        <th style="border: 1px solid black;text-align: center;height: 30px;width:15%;vertical-align:middle">Name</th>
        <th style="border: 1px solid black;text-align: center;height: 30px;width:34%;vertical-align:middle">What was done today</th>
        <th style="border: 1px solid black;text-align: center;height: 30px;width:34%;vertical-align:middle">Plan for tomorrow</th>
        <th style="border: 1px solid black;text-align: center;height: 30px;width:16%;vertical-align:middle">Impediments</th>
        <% if is_website_view %>
          <th style="border: 1px solid black;text-align: center;height: 30px;width:8%">Jira Updated</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
    <% today_statuses.keys.each_with_index do |user, index| %>
      <% status = today_statuses[user] %>
      <tr style="font-size:13px;background-color:<%= index % 2 !=0 ? 'rgb(204,204,204)' : 'white' %>">
        <td class="small" style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width: 15%;">
          <%=is_website_view ? (link_to user.name, edit_status_path(status.id)) : user.name%>
        </td>
        <td class="pivotal-column" style="word-wrap:break-word;border: 1px solid black;text-align:left;height:30px;padding-top:10px;padding-bottom:10px;width:34%">
          <% status.today_tasks.each do |task| %>
            <div style="margin: 10px 5px 5px 5px;">
              <strong><%=task.name%></strong>
              <%=formatted_description(task.description)%>
            </div>
          <% end %>
        </td>
        <td class="pivotal-column" style="word-wrap:break-word;border: 1px solid black;text-align:left;height:30px;padding-top:10px;padding-bottom:10px;width:34%">
          <% status.tomorrow_tasks.each do |task| %>
            <div style="margin: 10px 5px 5px 5px;">
              <strong><%=task.name%></strong>
              <%=formatted_description(task.description)%>
            </div>
          <% end %>
        </td>
        <td style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width:16%">
          <%=status.impediments%>
        </td>
        <% if is_website_view %>
          <td style="word-wrap:break-word;border: 1px solid black;text-align: center;height: 30px;width:8%">
            <%=status.tracker_updated == true ? 'Done' : ''%>
          </td>
          <!--<td style="border: 1px solid black;text-align: center;height: 30px;">
            <%#=link_to "Delete", status_path(status), :method => :delete%>
          </td>-->
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% unless is_website_view %>
    <div class="">
      <p>
        <br/><br/>
          Regards,
        <br/>
        Prashant Sahni
      </p>
    </div>
  <% end %>
</div>

app/views/status/_task_fields.html.erb
<div class="task-fields">
  <div class="form-group">
    <label for="">Title</label>
    <%=form.text_field :name, :class => 'form-control' %>
    <span class='error'>
      <%=
        status.errors["#{ status_task_type }_tasks.name"][0] if status && status.errors["#{ status_task_type }_tasks.name"]
      %>
    </span>
  </div>
  <div class="form-group">
    <label for="">Description</label>
    <%=form.text_area  :description, :class => 'form-control description-field',
                                     :rows => 2 
    %>
    <span class='error'>
      <%=
          status.errors["#{ status_task_type }_tasks.description"][0] if status && status.errors["#{ status_task_type }_tasks.name"]
      %>
    </span>
  </div>
  <%=form.hidden_field :task_type, :value => Task::TASK_TYPES[status_task_type.to_sym]%>
</div>
<div class="remove-task">
  <%=form.hidden_field :_destroy%>
  <%=link_to 'Remove', '/', :class => 'remove-task-link' if enable_destroy%>
</div>

app/views/status/all_status.html.erb
<div class="template">
  <div class="row">
    <% if @users_status.any? %>
      <h4>Following people have updated status today <%=Date.today.strftime("%m/%b/%Y")%></h4>
      <div class="margin-div"></div>
      <% @users_status.each do |status_user| %>
        <div class="col-md-12">
          <a class='no-text-decor list-font' href="<%=status_path(status_user)%>"><%=status_user.user.name%></a>
        </div>
      <% end %>
  </div>
  <% else %>
    <div class="flash flash-error">
        <%=flash[:error] || "Nobody has updated status yet"%>
    </div>
  <% end %>
</div>
<div class="margin-div"></div>
<div class="row">
  <%=link_to "Add-Status", new_status_path, :class => 'no-text-decor' %>
      |
  <%=link_to "See-Status-Report", status_report_status_index_path, :class => 'no-text-decor'%>
</div>

app/views/status/edit.html.erb
<%=render :partial => "form"%>

app/views/status/index.html.erb
<div>
  <a href="<%=new_status_path%>" class='major-link'>Create Your Status</a>
</div>

app/views/status/new.html.erb
<!--<div class='float-right bold-link'>-->
  <!--<%#=link_to "See People who updated status", '/all_status'%>-->
<!--</div>-->
<%=render :partial => "form"%>

app/views/status/show.html.erb
<div class='template no-gutter'>
  <div class="col-md-12">
    <label for="" class="main-label col-md-5">
      What was done today
    </label>
    <span class="edit-link-on-page col-md-4">
      <%=link_to "Edit", edit_status_path(@status)%>
    </span>
  </div>
  <div class="col-md-12">
    <% @status.today_tasks.each do |today_task|%>
      <div class="col-md-12">
        <strong><%=today_task.name%></strong>
      </div>
      <div class="col-md-12">
        <%=formatted_description(today_task.description)%>
      </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <label for="" class="main-label col-md-5">
      Plan for Tomorrow
    </label>
    <span class="edit-link-on-page col-md-4">
      <%=link_to "Edit", edit_status_path(@status)%>
    </span>
  </div>
  <div class="col-md-12">
    <% @status.tomorrow_tasks.each do |tomorrow_task|%>
      <div class="col-md-12">
        <strong><%=tomorrow_task.name%></strong>
      </div>
      <div class="col-md-12">
        <%=formatted_description(tomorrow_task.description)%>
      </div>
    <% end %>
  </div>
  <div class="col-md-12 top-space">
    <label for="" class="main-label col-md-5">Impediments</label>
    <div class="col-md-12">
      <%=@status.impediments.blank? ? 'No' : @status.impediments%>
    </div>
  </div>
  <div class="col-md-12 top-space">
    <label class="main-label col-md-5">Done</label>
    <div class="col-md-12">
      <%=@status.done == true ? 'Yes' : 'No'%>
    </div>
  </div>
  <div class="col-md-12 top-space">
    <label class="main-label col-md-5">Rally Updated</label>
    <div class="col-md-12">
      <%=@status.tracker_updated == true ? 'Yes' : 'No'%>
    </div>
  </div>
</div>

app/views/status/status_report.html.erb
<% if @today_statuses.blank? %>
  <h2>No info available</h2>
<% else %>
  <% if @users_not_updated_status && @users_not_updated_status.any? %>
    <div>
      <h3>Users who have not updated their status:</h3>
      <p>
        <%=@users_not_updated_status.collect(&:name).join(', ')%>
      </p>
    </div>
  <% end %>
  <h3>Status:</h3>
  <%=render :partial => 'report_template',
            :locals => {
              :today_statuses => @today_statuses,
              :risk_documents => @risk_documents,
              :is_website_view => true
            }
  %>
  <% if params[:action] != 'prev_status'%>
    <%#=render :partial => "form_for_email"%>
    <%#=link_to "Email View", status_report_status_index_path(:email_view => 1), :target => '_blank'%>
  <% end %>
<% end  %>

app/views/status/status_report_email.html.erb
<%=flash_html%>
<%=render :partial => 'report_template',
          :locals => {
            :today_statuses => @today_statuses,
            :risk_documents => @risk_documents, 
            :is_website_view => false
          }
%>